name: awesome_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: '^3.3.1'
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_native_splash: ^2.4.3
  flutter_svg: '^2.0.7'
  get: ^4.6.6
  hive: '^2.2.3'
  hive_flutter: '^1.1.0'
  hive_generator: '^2.0.1'
  path_provider: ^2.1.5
  shimmer: '^3.0.0'

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/resources/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/
    - lib/resources/fonts/

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: lib/resources/fonts/RobotoCondensed-Regular.ttf
        - asset: lib/resources/fonts/RobotoCondensed-Italic.ttf
          style: italic
        - asset: lib/resources/fonts/RobotoCondensed-Thin.ttf
          weight: 100
        - asset: lib/resources/fonts/RobotoCondensed-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/resources/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: lib/resources/fonts/RobotoCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/resources/fonts/RobotoCondensed-Medium.ttf
          weight: 500
        - asset: lib/resources/fonts/RobotoCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/resources/fonts/RobotoCondensed-SemiBold.ttf
          weight: 600
        - asset: lib/resources/fonts/RobotoCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/resources/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: lib/resources/fonts/RobotoCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/resources/fonts/RobotoCondensed-ExtraBold.ttf
          weight: 800
        - asset: lib/resources/fonts/RobotoCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/resources/fonts/RobotoCondensed-Black.ttf
          weight: 900
        - asset: lib/resources/fonts/RobotoCondensed-BlackItalic.ttf
          weight: 900
          style: italic
